[application]
name = "rayslash-me"
default_platform = "web"

out_dir = "dist"
asset_dir = "public"

[web.app]
title = "rayslash-me"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]
index_on_404 = true

[web.resource]
style = ["global.css"]
script = []

[web.resource.dev]
style = ["global.css"]
script = []
